language: node_js
dist: trusty
node_js:
  - "4"
  - "6"
  - "8.1.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g coveralls
script:
   - make
notifications:
  irc: "chat.freenode.net#brass-monkey"
after_success:
  - cat ./coverage/lcov.info | coveralls
