language: node_js
dist: trusty
node_js:
  - "6"
  - "8"
  - "9"
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g coveralls
  - greenkeeper-lockfile-update
script:
  - make
after_script:
  - greenkeeper-lockfile-upload
notifications:
  irc: "chat.freenode.net#bucharest-gold"
after_success:
  - cat ./coverage/lcov.info | coveralls
